name: a3data_challenge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  fpdart: ^0.5.0
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.18.0
  mockito: ^5.3.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
